# Generated by Django 5.1.1 on 2024-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Troop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("HP", models.IntegerField(max_length=5)),
                ("Dps", models.IntegerField(max_length=5)),
                ("SA", models.CharField(max_length=50)),
            ],
        ),
    ]
